### ISSUE TITLE
Mouse wheel does not work

### ISSUE THREAD

**Issue by Luxato** [per1234/MouseTo#1]
Mouse.move() third parameter should be amount to move scroll wheel.
It does not work when I'm using your library.

https://www.arduino.cc/en/Reference/MouseMove

Thanks for response

**Comment by per1234** [comment]
Hi, I'm trying to understand the issue you're having. Could you provide a short code example to demonstrate the problem please?

**Comment by per1234** [comment]
@Luxato I'm still waiting for feedback from you. I am willing to investigate any possible bugs but I need more information to know what the problem is.

**Comment by Luxato** [comment]
@per1234 Thanks, I will try to be more specific ASAP.

**Comment by per1234** [comment]
I'm going to close this due to lack of feedback.

I can see two different interpretations of the issue:

1. Merely that `MouseTo.Move()` doesn't have a parameter for moving the scroll wheel. This is not a functionality I intend to add for the following reasons:
  - The purpose of the library is to move the mouse pointer to absolute coordinates and I don't see how moving the scroll wheel is related to this in any way.
  - Adding that functionality would increase the overhead of the library.
  - I would have to make an arbitrary decision of when the scrolling should be done (start of the move, end of the move, or distributed throughout the move).
  - `Mouse.move()` can still be used to control the scroll wheel, thus not providing that does not limit the user in any way.
2. The use of the `MouseTo.move()` interferes with the use of `Mouse.move()` to control the scroll wheel. If this was the case I would consider it a bug and want to fix it. However, my tests have shown that use of `Mouse.move()` to control the scroll wheel still works fine while using this library. One thing to keep in mind is that (at least on my computer) the scroll wheel only works for the area of the window that the mouse pointer is hovering over. Thus if you have moved the pointer away from the target area using `MouseTo.move()` (or any other way), such as will happen when you home the mouse pointer, the scroll wheel will not work as you might intend.

If you are indeed experiencing a bug rather than interpretation 1 in the list above please provide more information and I will reopen this and investigate.
