### ISSUE TITLE
Display the position of the mouse pointer on any platform

### ISSUE THREAD

**Issue by tttapa** [per1234/MouseTo#3]
Hi, 

I was reading your ReadMe where you asked for applications that display the mouse pointer position. 
I'm not sure if you're still looking for help, but the simplest solution I could come up with is using HTML+JavaScript. Just save the following as an HTML file, open it in a browser, and hit F11 to go full screen. I've tried it in Google Chrome 71 on Ubuntu 16.04.

```html
<html>
<body>
    Mouse pointer position: (<span id="x">-</span>, <span id="y">-</span>)
</body>
<script>
    const x = document.getElementById("x");
    const y = document.getElementById("y");
    document.onmousemove = event => {
        x.textContent = event.pageX;
        y.textContent = event.pageY;
    };
</script>
</html>
```

Hope this is what you were looking for,
Pieter

**Comment by per1234** [comment]
Thanks so much! I was actually looking for help on this more than ever because I was recently informed that the program I previously recommended has disappeared from the Internet. I did a bit of searching around for alternatives but didn't come up with anything. It's strange because I'd expect there to be tons of options available.

I like the simplicity and compatibility with all OS of this solution. It is a bit inconvenient that it only works when the pointer is in the browser window. That's fine for the calibration test but it's a bit less convenient when you're trying to determine screen coordinates in other windows. You have to put the mouse pointer at the coordinate and then use the keyboard to switch to the browser window running your html file without moving the mouse. Well, that's not so bad.

**Comment by tttapa** [comment]
If you're on Linux, you can use the following command:
```sh
watch -t -n 0,01 xdotool getmouselocation
```
<sub>(The period or comma of the 0,01 seems to depend on the locale, so you might have to change it to a decimal point)</sub>

**Comment by tttapa** [comment]
Or if you're on Windows:
https://github.com/tttapa/MousePointer

**Comment by per1234** [comment]
Thanks! Those are exactly what I prefer, though I'll stick with recommending the HTML file as the primary solution since it's the easiest. The xdotool solution should also work on macOS. I added these to the readme, along with Android's built-in tool: https://github.com/per1234/MouseTo/commit/eb023681ca190529316f72e52af454006531e483
